version: "3"

services:
  mongo:
    container_name: crud-manager-product-service-mongo
    image: mongo:4
    restart: always
    ports:
      - 27000:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
